[project]
name = "performance-tests"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "faker>=40.28.1",
    "fastapi[standard]>=0.141.1",
    "gevent>=26.7.0",
    "grpcio>=1.82.1",
    "grpcio-tools>=1.82.1",
    "httpx>=0.28.1",
    "load-testing-hub>=0.6.0",
    "locust>=2.46.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
]

[tool.black]
line-length = 88
