"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CardType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CardTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CardType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CARD_TYPE_UNSPECIFIED: _CardType.ValueType  # 0
    CARD_TYPE_VIRTUAL: _CardType.ValueType  # 1
    CARD_TYPE_PHYSICAL: _CardType.ValueType  # 2

class CardType(_CardType, metaclass=_CardTypeEnumTypeWrapper): ...

CARD_TYPE_UNSPECIFIED: CardType.ValueType  # 0
CARD_TYPE_VIRTUAL: CardType.ValueType  # 1
CARD_TYPE_PHYSICAL: CardType.ValueType  # 2
global___CardType = CardType

class _CardStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CardStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CardStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CARD_STATUS_UNSPECIFIED: _CardStatus.ValueType  # 0
    CARD_STATUS_ACTIVE: _CardStatus.ValueType  # 1
    CARD_STATUS_FROZEN: _CardStatus.ValueType  # 2
    CARD_STATUS_CLOSED: _CardStatus.ValueType  # 3
    CARD_STATUS_BLOCKED: _CardStatus.ValueType  # 4

class CardStatus(_CardStatus, metaclass=_CardStatusEnumTypeWrapper): ...

CARD_STATUS_UNSPECIFIED: CardStatus.ValueType  # 0
CARD_STATUS_ACTIVE: CardStatus.ValueType  # 1
CARD_STATUS_FROZEN: CardStatus.ValueType  # 2
CARD_STATUS_CLOSED: CardStatus.ValueType  # 3
CARD_STATUS_BLOCKED: CardStatus.ValueType  # 4
global___CardStatus = CardStatus

class _CardPaymentSystem:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CardPaymentSystemEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CardPaymentSystem.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CARD_PAYMENT_SYSTEM_UNSPECIFIED: _CardPaymentSystem.ValueType  # 0
    CARD_PAYMENT_SYSTEM_MASTERCARD: _CardPaymentSystem.ValueType  # 1
    CARD_PAYMENT_SYSTEM_VISA: _CardPaymentSystem.ValueType  # 2

class CardPaymentSystem(_CardPaymentSystem, metaclass=_CardPaymentSystemEnumTypeWrapper): ...

CARD_PAYMENT_SYSTEM_UNSPECIFIED: CardPaymentSystem.ValueType  # 0
CARD_PAYMENT_SYSTEM_MASTERCARD: CardPaymentSystem.ValueType  # 1
CARD_PAYMENT_SYSTEM_VISA: CardPaymentSystem.ValueType  # 2
global___CardPaymentSystem = CardPaymentSystem

@typing.final
class Card(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PIN_FIELD_NUMBER: builtins.int
    CVV_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CARD_NUMBER_FIELD_NUMBER: builtins.int
    CARD_HOLDER_FIELD_NUMBER: builtins.int
    EXPIRY_DATE_FIELD_NUMBER: builtins.int
    PAYMENT_SYSTEM_FIELD_NUMBER: builtins.int
    id: builtins.str
    pin: builtins.str
    cvv: builtins.str
    type: global___CardType.ValueType
    status: global___CardStatus.ValueType
    account_id: builtins.str
    card_number: builtins.str
    card_holder: builtins.str
    expiry_date: builtins.str
    payment_system: global___CardPaymentSystem.ValueType
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        pin: builtins.str = ...,
        cvv: builtins.str = ...,
        type: global___CardType.ValueType = ...,
        status: global___CardStatus.ValueType = ...,
        account_id: builtins.str = ...,
        card_number: builtins.str = ...,
        card_holder: builtins.str = ...,
        expiry_date: builtins.str = ...,
        payment_system: global___CardPaymentSystem.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "card_holder", b"card_holder", "card_number", b"card_number", "cvv", b"cvv", "expiry_date", b"expiry_date", "id", b"id", "payment_system", b"payment_system", "pin", b"pin", "status", b"status", "type", b"type"]) -> None: ...

global___Card = Card
