# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/cards/card.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/cards/card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#contracts/services/cards/card.proto\x12\x18\x63ontracts.services.cards\"\xac\x02\n\x04\x43\x61rd\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\x12\x30\n\x04type\x18\x04 \x01(\x0e\x32\".contracts.services.cards.CardType\x12\x34\n\x06status\x18\x05 \x01(\x0e\x32$.contracts.services.cards.CardStatus\x12\x12\n\naccount_id\x18\x06 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x07 \x01(\t\x12\x13\n\x0b\x63\x61rd_holder\x18\x08 \x01(\t\x12\x13\n\x0b\x65xpiry_date\x18\t \x01(\t\x12\x43\n\x0epayment_system\x18\n \x01(\x0e\x32+.contracts.services.cards.CardPaymentSystem*T\n\x08\x43\x61rdType\x12\x19\n\x15\x43\x41RD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43\x41RD_TYPE_VIRTUAL\x10\x01\x12\x16\n\x12\x43\x41RD_TYPE_PHYSICAL\x10\x02*\x8a\x01\n\nCardStatus\x12\x1b\n\x17\x43\x41RD_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12\x43\x41RD_STATUS_ACTIVE\x10\x01\x12\x16\n\x12\x43\x41RD_STATUS_FROZEN\x10\x02\x12\x16\n\x12\x43\x41RD_STATUS_CLOSED\x10\x03\x12\x17\n\x13\x43\x41RD_STATUS_BLOCKED\x10\x04*z\n\x11\x43\x61rdPaymentSystem\x12#\n\x1f\x43\x41RD_PAYMENT_SYSTEM_UNSPECIFIED\x10\x00\x12\"\n\x1e\x43\x41RD_PAYMENT_SYSTEM_MASTERCARD\x10\x01\x12\x1c\n\x18\x43\x41RD_PAYMENT_SYSTEM_VISA\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.cards.card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARDTYPE']._serialized_start=368
  _globals['_CARDTYPE']._serialized_end=452
  _globals['_CARDSTATUS']._serialized_start=455
  _globals['_CARDSTATUS']._serialized_end=593
  _globals['_CARDPAYMENTSYSTEM']._serialized_start=595
  _globals['_CARDPAYMENTSYSTEM']._serialized_end=717
  _globals['_CARD']._serialized_start=66
  _globals['_CARD']._serialized_end=366
# @@protoc_insertion_point(module_scope)
