# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/cards/cards_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/cards/cards_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.cards import rpc_get_card_pb2 as contracts_dot_services_dot_cards_dot_rpc__get__card__pb2
from contracts.services.cards import rpc_get_cards_pb2 as contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2
from contracts.services.cards import rpc_create_card_pb2 as contracts_dot_services_dot_cards_dot_rpc__create__card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,contracts/services/cards/cards_service.proto\x12\x18\x63ontracts.services.cards\x1a+contracts/services/cards/rpc_get_card.proto\x1a,contracts/services/cards/rpc_get_cards.proto\x1a.contracts/services/cards/rpc_create_card.proto2\xba\x02\n\x0c\x43\x61rdsService\x12^\n\x07GetCard\x12(.contracts.services.cards.GetCardRequest\x1a).contracts.services.cards.GetCardResponse\x12\x61\n\x08GetCards\x12).contracts.services.cards.GetCardsRequest\x1a*.contracts.services.cards.GetCardsResponse\x12g\n\nCreateCard\x12+.contracts.services.cards.CreateCardRequest\x1a,.contracts.services.cards.CreateCardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.cards.cards_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARDSSERVICE']._serialized_start=214
  _globals['_CARDSSERVICE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
