# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.cards import rpc_create_card_pb2 as contracts_dot_services_dot_cards_dot_rpc__create__card__pb2
from contracts.services.cards import rpc_get_card_pb2 as contracts_dot_services_dot_cards_dot_rpc__get__card__pb2
from contracts.services.cards import rpc_get_cards_pb2 as contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/cards/cards_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CardsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCard = channel.unary_unary(
                '/contracts.services.cards.CardsService/GetCard',
                request_serializer=contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardResponse.FromString,
                _registered_method=True)
        self.GetCards = channel.unary_unary(
                '/contracts.services.cards.CardsService/GetCards',
                request_serializer=contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsResponse.FromString,
                _registered_method=True)
        self.CreateCard = channel.unary_unary(
                '/contracts.services.cards.CardsService/CreateCard',
                request_serializer=contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardResponse.FromString,
                _registered_method=True)


class CardsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCard,
                    request_deserializer=contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardRequest.FromString,
                    response_serializer=contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardResponse.SerializeToString,
            ),
            'GetCards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCards,
                    request_deserializer=contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsRequest.FromString,
                    response_serializer=contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsResponse.SerializeToString,
            ),
            'CreateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCard,
                    request_deserializer=contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardRequest.FromString,
                    response_serializer=contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.cards.CardsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.cards.CardsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.cards.CardsService/GetCard',
            contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardRequest.SerializeToString,
            contracts_dot_services_dot_cards_dot_rpc__get__card__pb2.GetCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.cards.CardsService/GetCards',
            contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsRequest.SerializeToString,
            contracts_dot_services_dot_cards_dot_rpc__get__cards__pb2.GetCardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.cards.CardsService/CreateCard',
            contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardRequest.SerializeToString,
            contracts_dot_services_dot_cards_dot_rpc__create__card__pb2.CreateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
