"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.cards.card_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateCardRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PIN_FIELD_NUMBER: builtins.int
    CVV_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CARD_NUMBER_FIELD_NUMBER: builtins.int
    CARD_HOLDER_FIELD_NUMBER: builtins.int
    EXPIRY_DATE_FIELD_NUMBER: builtins.int
    PAYMENT_SYSTEM_FIELD_NUMBER: builtins.int
    pin: builtins.str
    cvv: builtins.str
    type: contracts.services.cards.card_pb2.CardType.ValueType
    status: contracts.services.cards.card_pb2.CardStatus.ValueType
    account_id: builtins.str
    card_number: builtins.str
    card_holder: builtins.str
    expiry_date: builtins.str
    payment_system: contracts.services.cards.card_pb2.CardPaymentSystem.ValueType
    def __init__(
        self,
        *,
        pin: builtins.str = ...,
        cvv: builtins.str = ...,
        type: contracts.services.cards.card_pb2.CardType.ValueType = ...,
        status: contracts.services.cards.card_pb2.CardStatus.ValueType = ...,
        account_id: builtins.str = ...,
        card_number: builtins.str = ...,
        card_holder: builtins.str = ...,
        expiry_date: builtins.str = ...,
        payment_system: contracts.services.cards.card_pb2.CardPaymentSystem.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "card_holder", b"card_holder", "card_number", b"card_number", "cvv", b"cvv", "expiry_date", b"expiry_date", "payment_system", b"payment_system", "pin", b"pin", "status", b"status", "type", b"type"]) -> None: ...

global___CreateCardRequest = CreateCardRequest

@typing.final
class CreateCardResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_FIELD_NUMBER: builtins.int
    @property
    def card(self) -> contracts.services.cards.card_pb2.Card: ...
    def __init__(
        self,
        *,
        card: contracts.services.cards.card_pb2.Card | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["card", b"card"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["card", b"card"]) -> None: ...

global___CreateCardResponse = CreateCardResponse
