# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/cards/rpc_get_cards.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/cards/rpc_get_cards.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.cards import card_pb2 as contracts_dot_services_dot_cards_dot_card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,contracts/services/cards/rpc_get_cards.proto\x12\x18\x63ontracts.services.cards\x1a#contracts/services/cards/card.proto\"%\n\x0fGetCardsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"A\n\x10GetCardsResponse\x12-\n\x05\x63\x61rds\x18\x01 \x03(\x0b\x32\x1e.contracts.services.cards.Cardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.cards.rpc_get_cards_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCARDSREQUEST']._serialized_start=111
  _globals['_GETCARDSREQUEST']._serialized_end=148
  _globals['_GETCARDSRESPONSE']._serialized_start=150
  _globals['_GETCARDSRESPONSE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
