"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import contracts.services.cards.card_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetCardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___GetCardsRequest = GetCardsRequest

@typing.final
class GetCardsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARDS_FIELD_NUMBER: builtins.int
    @property
    def cards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[contracts.services.cards.card_pb2.Card]: ...
    def __init__(
        self,
        *,
        cards: collections.abc.Iterable[contracts.services.cards.card_pb2.Card] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cards", b"cards"]) -> None: ...

global___GetCardsResponse = GetCardsResponse
