# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/cards/rpc_create_card.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/cards/rpc_create_card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.cards import card_pb2 as contracts_dot_services_dot_cards_dot_card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.contracts/services/cards/rpc_create_card.proto\x12\x18\x63ontracts.services.cards\x1a#contracts/services/cards/card.proto\"\xad\x02\n\x11\x43reateCardRequest\x12\x0b\n\x03pin\x18\x01 \x01(\t\x12\x0b\n\x03\x63vv\x18\x02 \x01(\t\x12\x30\n\x04type\x18\x03 \x01(\x0e\x32\".contracts.services.cards.CardType\x12\x34\n\x06status\x18\x04 \x01(\x0e\x32$.contracts.services.cards.CardStatus\x12\x12\n\naccount_id\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x06 \x01(\t\x12\x13\n\x0b\x63\x61rd_holder\x18\x07 \x01(\t\x12\x13\n\x0b\x65xpiry_date\x18\x08 \x01(\t\x12\x43\n\x0epayment_system\x18\t \x01(\x0e\x32+.contracts.services.cards.CardPaymentSystem\"B\n\x12\x43reateCardResponse\x12,\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x1e.contracts.services.cards.Cardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.cards.rpc_create_card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECARDREQUEST']._serialized_start=114
  _globals['_CREATECARDREQUEST']._serialized_end=415
  _globals['_CREATECARDRESPONSE']._serialized_start=417
  _globals['_CREATECARDRESPONSE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
