# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/cards/rpc_get_card.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/cards/rpc_get_card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.cards import card_pb2 as contracts_dot_services_dot_cards_dot_card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+contracts/services/cards/rpc_get_card.proto\x12\x18\x63ontracts.services.cards\x1a#contracts/services/cards/card.proto\"\x1c\n\x0eGetCardRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\x0fGetCardResponse\x12,\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x1e.contracts.services.cards.Cardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.cards.rpc_get_card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCARDREQUEST']._serialized_start=110
  _globals['_GETCARDREQUEST']._serialized_end=138
  _globals['_GETCARDRESPONSE']._serialized_start=140
  _globals['_GETCARDRESPONSE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
