"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.cards.card_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetCardRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetCardRequest = GetCardRequest

@typing.final
class GetCardResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_FIELD_NUMBER: builtins.int
    @property
    def card(self) -> contracts.services.cards.card_pb2.Card: ...
    def __init__(
        self,
        *,
        card: contracts.services.cards.card_pb2.Card | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["card", b"card"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["card", b"card"]) -> None: ...

global___GetCardResponse = GetCardResponse
