"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.users.user_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    PHONE_NUMBER_FIELD_NUMBER: builtins.int
    email: builtins.str
    last_name: builtins.str
    first_name: builtins.str
    middle_name: builtins.str
    phone_number: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        last_name: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str = ...,
        phone_number: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "first_name", b"first_name", "last_name", b"last_name", "middle_name", b"middle_name", "phone_number", b"phone_number"]) -> None: ...

global___CreateUserRequest = CreateUserRequest

@typing.final
class CreateUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> contracts.services.users.user_pb2.User: ...
    def __init__(
        self,
        *,
        user: contracts.services.users.user_pb2.User | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user", b"user"]) -> None: ...

global___CreateUserResponse = CreateUserResponse
