"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import contracts.services.accounts.account_pb2
import contracts.services.cards.card_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AccountView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    CARDS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    id: builtins.str
    type: contracts.services.accounts.account_pb2.AccountType.ValueType
    status: contracts.services.accounts.account_pb2.AccountStatus.ValueType
    balance: builtins.float
    @property
    def cards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[contracts.services.cards.card_pb2.Card]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: contracts.services.accounts.account_pb2.AccountType.ValueType = ...,
        cards: collections.abc.Iterable[contracts.services.cards.card_pb2.Card] | None = ...,
        status: contracts.services.accounts.account_pb2.AccountStatus.ValueType = ...,
        balance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balance", b"balance", "cards", b"cards", "id", b"id", "status", b"status", "type", b"type"]) -> None: ...

global___AccountView = AccountView
