# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.gateway.accounts import rpc_get_accounts_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2
from contracts.services.gateway.accounts import rpc_open_credit_card_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2
from contracts.services.gateway.accounts import rpc_open_debit_card_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2
from contracts.services.gateway.accounts import rpc_open_deposit_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2
from contracts.services.gateway.accounts import rpc_open_savings_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/gateway/accounts/accounts_gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountsGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccounts = channel.unary_unary(
                '/contracts.services.gateway.accounts.AccountsGatewayService/GetAccounts',
                request_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.FromString,
                _registered_method=True)
        self.OpenDepositAccount = channel.unary_unary(
                '/contracts.services.gateway.accounts.AccountsGatewayService/OpenDepositAccount',
                request_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountResponse.FromString,
                _registered_method=True)
        self.OpenSavingsAccount = channel.unary_unary(
                '/contracts.services.gateway.accounts.AccountsGatewayService/OpenSavingsAccount',
                request_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountResponse.FromString,
                _registered_method=True)
        self.OpenDebitCardAccount = channel.unary_unary(
                '/contracts.services.gateway.accounts.AccountsGatewayService/OpenDebitCardAccount',
                request_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountResponse.FromString,
                _registered_method=True)
        self.OpenCreditCardAccount = channel.unary_unary(
                '/contracts.services.gateway.accounts.AccountsGatewayService/OpenCreditCardAccount',
                request_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountResponse.FromString,
                _registered_method=True)


class AccountsGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDepositAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSavingsAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDebitCardAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenCreditCardAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountsGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.SerializeToString,
            ),
            'OpenDepositAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDepositAccount,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountResponse.SerializeToString,
            ),
            'OpenSavingsAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSavingsAccount,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountResponse.SerializeToString,
            ),
            'OpenDebitCardAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDebitCardAccount,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountResponse.SerializeToString,
            ),
            'OpenCreditCardAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCreditCardAccount,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.gateway.accounts.AccountsGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.gateway.accounts.AccountsGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountsGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.accounts.AccountsGatewayService/GetAccounts',
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenDepositAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.accounts.AccountsGatewayService/OpenDepositAccount',
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2.OpenDepositAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSavingsAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.accounts.AccountsGatewayService/OpenSavingsAccount',
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2.OpenSavingsAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenDebitCardAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.accounts.AccountsGatewayService/OpenDebitCardAccount',
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2.OpenDebitCardAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenCreditCardAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.accounts.AccountsGatewayService/OpenCreditCardAccount',
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2.OpenCreditCardAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
