# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/accounts/accounts_gateway_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/accounts/accounts_gateway_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.gateway.accounts import rpc_get_accounts_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__get__accounts__pb2
from contracts.services.gateway.accounts import rpc_open_deposit_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__deposit__account__pb2
from contracts.services.gateway.accounts import rpc_open_savings_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__savings__account__pb2
from contracts.services.gateway.accounts import rpc_open_debit_card_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__debit__card__account__pb2
from contracts.services.gateway.accounts import rpc_open_credit_card_account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_rpc__open__credit__card__account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcontracts/services/gateway/accounts/accounts_gateway_service.proto\x12#contracts.services.gateway.accounts\x1a:contracts/services/gateway/accounts/rpc_get_accounts.proto\x1a\x42\x63ontracts/services/gateway/accounts/rpc_open_deposit_account.proto\x1a\x42\x63ontracts/services/gateway/accounts/rpc_open_savings_account.proto\x1a\x45\x63ontracts/services/gateway/accounts/rpc_open_debit_card_account.proto\x1a\x46\x63ontracts/services/gateway/accounts/rpc_open_credit_card_account.proto2\x8a\x06\n\x16\x41\x63\x63ountsGatewayService\x12\x80\x01\n\x0bGetAccounts\x12\x37.contracts.services.gateway.accounts.GetAccountsRequest\x1a\x38.contracts.services.gateway.accounts.GetAccountsResponse\x12\x95\x01\n\x12OpenDepositAccount\x12>.contracts.services.gateway.accounts.OpenDepositAccountRequest\x1a?.contracts.services.gateway.accounts.OpenDepositAccountResponse\x12\x95\x01\n\x12OpenSavingsAccount\x12>.contracts.services.gateway.accounts.OpenSavingsAccountRequest\x1a?.contracts.services.gateway.accounts.OpenSavingsAccountResponse\x12\x9b\x01\n\x14OpenDebitCardAccount\x12@.contracts.services.gateway.accounts.OpenDebitCardAccountRequest\x1a\x41.contracts.services.gateway.accounts.OpenDebitCardAccountResponse\x12\x9e\x01\n\x15OpenCreditCardAccount\x12\x41.contracts.services.gateway.accounts.OpenCreditCardAccountRequest\x1a\x42.contracts.services.gateway.accounts.OpenCreditCardAccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.accounts.accounts_gateway_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTSGATEWAYSERVICE']._serialized_start=447
  _globals['_ACCOUNTSGATEWAYSERVICE']._serialized_end=1225
# @@protoc_insertion_point(module_scope)
