# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/accounts/rpc_open_credit_card_account.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/accounts/rpc_open_credit_card_account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.gateway.accounts import account_pb2 as contracts_dot_services_dot_gateway_dot_accounts_dot_account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcontracts/services/gateway/accounts/rpc_open_credit_card_account.proto\x12#contracts.services.gateway.accounts\x1a\x31\x63ontracts/services/gateway/accounts/account.proto\"/\n\x1cOpenCreditCardAccountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"b\n\x1dOpenCreditCardAccountResponse\x12\x41\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x30.contracts.services.gateway.accounts.AccountViewb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.accounts.rpc_open_credit_card_account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENCREDITCARDACCOUNTREQUEST']._serialized_start=162
  _globals['_OPENCREDITCARDACCOUNTREQUEST']._serialized_end=209
  _globals['_OPENCREDITCARDACCOUNTRESPONSE']._serialized_start=211
  _globals['_OPENCREDITCARDACCOUNTRESPONSE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
