"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.documents.contracts.contract_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateContractRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    content: builtins.bytes
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        content: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "content", b"content"]) -> None: ...

global___CreateContractRequest = CreateContractRequest

@typing.final
class CreateContractResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_FIELD_NUMBER: builtins.int
    @property
    def contract(self) -> contracts.services.documents.contracts.contract_pb2.Contract: ...
    def __init__(
        self,
        *,
        contract: contracts.services.documents.contracts.contract_pb2.Contract | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["contract", b"contract"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contract", b"contract"]) -> None: ...

global___CreateContractResponse = CreateContractResponse
