# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/documents/contracts/rpc_get_contract.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/documents/contracts/rpc_get_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.documents.contracts import contract_pb2 as contracts_dot_services_dot_documents_dot_contracts_dot_contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=contracts/services/documents/contracts/rpc_get_contract.proto\x12&contracts.services.documents.contracts\x1a\x35\x63ontracts/services/documents/contracts/contract.proto\"(\n\x12GetContractRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"Y\n\x13GetContractResponse\x12\x42\n\x08\x63ontract\x18\x01 \x01(\x0b\x32\x30.contracts.services.documents.contracts.Contractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.documents.contracts.rpc_get_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONTRACTREQUEST']._serialized_start=160
  _globals['_GETCONTRACTREQUEST']._serialized_end=200
  _globals['_GETCONTRACTRESPONSE']._serialized_start=202
  _globals['_GETCONTRACTRESPONSE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
