# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.gateway.documents import rpc_get_contract_document_pb2 as contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2
from contracts.services.gateway.documents import rpc_get_tariff_document_pb2 as contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/gateway/documents/documents_gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentsGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTariffDocument = channel.unary_unary(
                '/contracts.services.gateway.documents.DocumentsGatewayService/GetTariffDocument',
                request_serializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentResponse.FromString,
                _registered_method=True)
        self.GetContractDocument = channel.unary_unary(
                '/contracts.services.gateway.documents.DocumentsGatewayService/GetContractDocument',
                request_serializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentResponse.FromString,
                _registered_method=True)


class DocumentsGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTariffDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContractDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentsGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTariffDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTariffDocument,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentResponse.SerializeToString,
            ),
            'GetContractDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContractDocument,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.gateway.documents.DocumentsGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.gateway.documents.DocumentsGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentsGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTariffDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.documents.DocumentsGatewayService/GetTariffDocument',
            contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2.GetTariffDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContractDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.documents.DocumentsGatewayService/GetContractDocument',
            contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2.GetContractDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
