# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/documents/documents_gateway_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/documents/documents_gateway_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.gateway.documents import rpc_get_tariff_document_pb2 as contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__tariff__document__pb2
from contracts.services.gateway.documents import rpc_get_contract_document_pb2 as contracts_dot_services_dot_gateway_dot_documents_dot_rpc__get__contract__document__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcontracts/services/gateway/documents/documents_gateway_service.proto\x12$contracts.services.gateway.documents\x1a\x42\x63ontracts/services/gateway/documents/rpc_get_tariff_document.proto\x1a\x44\x63ontracts/services/gateway/documents/rpc_get_contract_document.proto2\xcd\x02\n\x17\x44ocumentsGatewayService\x12\x94\x01\n\x11GetTariffDocument\x12>.contracts.services.gateway.documents.GetTariffDocumentRequest\x1a?.contracts.services.gateway.documents.GetTariffDocumentResponse\x12\x9a\x01\n\x13GetContractDocument\x12@.contracts.services.gateway.documents.GetContractDocumentRequest\x1a\x41.contracts.services.gateway.documents.GetContractDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.documents.documents_gateway_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTSGATEWAYSERVICE']._serialized_start=249
  _globals['_DOCUMENTSGATEWAYSERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
