# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/documents/rpc_get_tariff_document.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/documents/rpc_get_tariff_document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.documents.tariffs import tariff_pb2 as contracts_dot_services_dot_documents_dot_tariffs_dot_tariff__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcontracts/services/gateway/documents/rpc_get_tariff_document.proto\x12$contracts.services.gateway.documents\x1a\x31\x63ontracts/services/documents/tariffs/tariff.proto\".\n\x18GetTariffDocumentRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"Y\n\x19GetTariffDocumentResponse\x12<\n\x06tariff\x18\x01 \x01(\x0b\x32,.contracts.services.documents.tariffs.Tariffb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.documents.rpc_get_tariff_document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTARIFFDOCUMENTREQUEST']._serialized_start=159
  _globals['_GETTARIFFDOCUMENTREQUEST']._serialized_end=205
  _globals['_GETTARIFFDOCUMENTRESPONSE']._serialized_start=207
  _globals['_GETTARIFFDOCUMENTRESPONSE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
