"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.documents.contracts.contract_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetContractDocumentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___GetContractDocumentRequest = GetContractDocumentRequest

@typing.final
class GetContractDocumentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_FIELD_NUMBER: builtins.int
    @property
    def contract(self) -> contracts.services.documents.contracts.contract_pb2.Contract: ...
    def __init__(
        self,
        *,
        contract: contracts.services.documents.contracts.contract_pb2.Contract | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["contract", b"contract"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contract", b"contract"]) -> None: ...

global___GetContractDocumentResponse = GetContractDocumentResponse
