"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    MIDDLE_NAME_FIELD_NUMBER: builtins.int
    PHONE_NUMBER_FIELD_NUMBER: builtins.int
    id: builtins.str
    email: builtins.str
    last_name: builtins.str
    first_name: builtins.str
    middle_name: builtins.str
    phone_number: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        email: builtins.str = ...,
        last_name: builtins.str = ...,
        first_name: builtins.str = ...,
        middle_name: builtins.str = ...,
        phone_number: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "first_name", b"first_name", "id", b"id", "last_name", b"last_name", "middle_name", b"middle_name", "phone_number", b"phone_number"]) -> None: ...

global___User = User
