"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OperationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPERATION_TYPE_UNSPECIFIED: _OperationType.ValueType  # 0
    OPERATION_TYPE_FEE: _OperationType.ValueType  # 1
    OPERATION_TYPE_TOP_UP: _OperationType.ValueType  # 3
    OPERATION_TYPE_PURCHASE: _OperationType.ValueType  # 4
    OPERATION_TYPE_CASHBACK: _OperationType.ValueType  # 5
    OPERATION_TYPE_TRANSFER: _OperationType.ValueType  # 6
    OPERATION_TYPE_BILL_PAYMENT: _OperationType.ValueType  # 7
    OPERATION_TYPE_CASH_WITHDRAWAL: _OperationType.ValueType  # 8

class OperationType(_OperationType, metaclass=_OperationTypeEnumTypeWrapper): ...

OPERATION_TYPE_UNSPECIFIED: OperationType.ValueType  # 0
OPERATION_TYPE_FEE: OperationType.ValueType  # 1
OPERATION_TYPE_TOP_UP: OperationType.ValueType  # 3
OPERATION_TYPE_PURCHASE: OperationType.ValueType  # 4
OPERATION_TYPE_CASHBACK: OperationType.ValueType  # 5
OPERATION_TYPE_TRANSFER: OperationType.ValueType  # 6
OPERATION_TYPE_BILL_PAYMENT: OperationType.ValueType  # 7
OPERATION_TYPE_CASH_WITHDRAWAL: OperationType.ValueType  # 8
global___OperationType = OperationType

class _OperationStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OPERATION_STATUS_UNSPECIFIED: _OperationStatus.ValueType  # 0
    OPERATION_STATUS_IN_PROGRESS: _OperationStatus.ValueType  # 1
    OPERATION_STATUS_COMPLETED: _OperationStatus.ValueType  # 2
    OPERATION_STATUS_FAILED: _OperationStatus.ValueType  # 3

class OperationStatus(_OperationStatus, metaclass=_OperationStatusEnumTypeWrapper): ...

OPERATION_STATUS_UNSPECIFIED: OperationStatus.ValueType  # 0
OPERATION_STATUS_IN_PROGRESS: OperationStatus.ValueType  # 1
OPERATION_STATUS_COMPLETED: OperationStatus.ValueType  # 2
OPERATION_STATUS_FAILED: OperationStatus.ValueType  # 3
global___OperationStatus = OperationStatus

@typing.final
class Operation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    CARD_ID_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    type: global___OperationType.ValueType
    status: global___OperationStatus.ValueType
    amount: builtins.float
    card_id: builtins.str
    category: builtins.str
    created_at: builtins.str
    account_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: global___OperationType.ValueType = ...,
        status: global___OperationStatus.ValueType = ...,
        amount: builtins.float = ...,
        card_id: builtins.str = ...,
        category: builtins.str = ...,
        created_at: builtins.str = ...,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "amount", b"amount", "card_id", b"card_id", "category", b"category", "created_at", b"created_at", "id", b"id", "status", b"status", "type", b"type"]) -> None: ...

global___Operation = Operation
