# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.operations import rpc_create_operation_pb2 as contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2
from contracts.services.operations import rpc_get_operation_pb2 as contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2
from contracts.services.operations import rpc_get_operations_pb2 as contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2
from contracts.services.operations import rpc_get_operations_summary_pb2 as contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/operations/operations_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOperation = channel.unary_unary(
                '/contracts.services.operations.OperationsService/GetOperation',
                request_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.GetOperations = channel.unary_unary(
                '/contracts.services.operations.OperationsService/GetOperations',
                request_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.FromString,
                _registered_method=True)
        self.CreateOperation = channel.unary_unary(
                '/contracts.services.operations.OperationsService/CreateOperation',
                request_serializer=contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationResponse.FromString,
                _registered_method=True)
        self.GetOperationsSummary = channel.unary_unary(
                '/contracts.services.operations.OperationsService/GetOperationsSummary',
                request_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.FromString,
                _registered_method=True)


class OperationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.SerializeToString,
            ),
            'GetOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperations,
                    request_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.FromString,
                    response_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.SerializeToString,
            ),
            'CreateOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOperation,
                    request_deserializer=contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationResponse.SerializeToString,
            ),
            'GetOperationsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationsSummary,
                    request_deserializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.FromString,
                    response_serializer=contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.operations.OperationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.operations.OperationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.operations.OperationsService/GetOperation',
            contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.SerializeToString,
            contracts_dot_services_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.operations.OperationsService/GetOperations',
            contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.SerializeToString,
            contracts_dot_services_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.operations.OperationsService/CreateOperation',
            contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationRequest.SerializeToString,
            contracts_dot_services_dot_operations_dot_rpc__create__operation__pb2.CreateOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.operations.OperationsService/GetOperationsSummary',
            contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.SerializeToString,
            contracts_dot_services_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
