# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/operations/operation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/operations/operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-contracts/services/operations/operation.proto\x12\x1d\x63ontracts.services.operations\"\xee\x01\n\tOperation\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\x04type\x18\x02 \x01(\x0e\x32,.contracts.services.operations.OperationType\x12>\n\x06status\x18\x03 \x01(\x0e\x32..contracts.services.operations.OperationStatus\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0f\n\x07\x63\x61rd_id\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\naccount_id\x18\x08 \x01(\t*\xfe\x01\n\rOperationType\x12\x1e\n\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12OPERATION_TYPE_FEE\x10\x01\x12\x19\n\x15OPERATION_TYPE_TOP_UP\x10\x03\x12\x1b\n\x17OPERATION_TYPE_PURCHASE\x10\x04\x12\x1b\n\x17OPERATION_TYPE_CASHBACK\x10\x05\x12\x1b\n\x17OPERATION_TYPE_TRANSFER\x10\x06\x12\x1f\n\x1bOPERATION_TYPE_BILL_PAYMENT\x10\x07\x12\"\n\x1eOPERATION_TYPE_CASH_WITHDRAWAL\x10\x08*\x92\x01\n\x0fOperationStatus\x12 \n\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12 \n\x1cOPERATION_STATUS_IN_PROGRESS\x10\x01\x12\x1e\n\x1aOPERATION_STATUS_COMPLETED\x10\x02\x12\x1b\n\x17OPERATION_STATUS_FAILED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.operations.operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONTYPE']._serialized_start=322
  _globals['_OPERATIONTYPE']._serialized_end=576
  _globals['_OPERATIONSTATUS']._serialized_start=579
  _globals['_OPERATIONSTATUS']._serialized_end=725
  _globals['_OPERATION']._serialized_start=81
  _globals['_OPERATION']._serialized_end=319
# @@protoc_insertion_point(module_scope)
