"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OperationsSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPENT_AMOUNT_FIELD_NUMBER: builtins.int
    RECEIVED_AMOUNT_FIELD_NUMBER: builtins.int
    CASHBACK_AMOUNT_FIELD_NUMBER: builtins.int
    spent_amount: builtins.float
    received_amount: builtins.float
    cashback_amount: builtins.float
    def __init__(
        self,
        *,
        spent_amount: builtins.float = ...,
        received_amount: builtins.float = ...,
        cashback_amount: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cashback_amount", b"cashback_amount", "received_amount", b"received_amount", "spent_amount", b"spent_amount"]) -> None: ...

global___OperationsSummary = OperationsSummary
