"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.operations.operations_summary_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetOperationsSummaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___GetOperationsSummaryRequest = GetOperationsSummaryRequest

@typing.final
class GetOperationsSummaryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: builtins.int
    @property
    def summary(self) -> contracts.services.operations.operations_summary_pb2.OperationsSummary: ...
    def __init__(
        self,
        *,
        summary: contracts.services.operations.operations_summary_pb2.OperationsSummary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["summary", b"summary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["summary", b"summary"]) -> None: ...

global___GetOperationsSummaryResponse = GetOperationsSummaryResponse
