# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/operations/rpc_get_operation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/operations/rpc_get_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.operations import operation_pb2 as contracts_dot_services_dot_operations_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5contracts/services/operations/rpc_get_operation.proto\x12\x1d\x63ontracts.services.operations\x1a-contracts/services/operations/operation.proto\"!\n\x13GetOperationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"S\n\x14GetOperationResponse\x12;\n\toperation\x18\x01 \x01(\x0b\x32(.contracts.services.operations.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.operations.rpc_get_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOPERATIONREQUEST']._serialized_start=135
  _globals['_GETOPERATIONREQUEST']._serialized_end=168
  _globals['_GETOPERATIONRESPONSE']._serialized_start=170
  _globals['_GETOPERATIONRESPONSE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
