# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/operations/rpc_get_operations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/operations/rpc_get_operations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.operations import operation_pb2 as contracts_dot_services_dot_operations_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6contracts/services/operations/rpc_get_operations.proto\x12\x1d\x63ontracts.services.operations\x1a-contracts/services/operations/operation.proto\"*\n\x14GetOperationsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"U\n\x15GetOperationsResponse\x12<\n\noperations\x18\x01 \x03(\x0b\x32(.contracts.services.operations.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.operations.rpc_get_operations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOPERATIONSREQUEST']._serialized_start=136
  _globals['_GETOPERATIONSREQUEST']._serialized_end=178
  _globals['_GETOPERATIONSRESPONSE']._serialized_start=180
  _globals['_GETOPERATIONSRESPONSE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
