# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.gateway.cards import rpc_issue_physical_card_pb2 as contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2
from contracts.services.gateway.cards import rpc_issue_virtual_card_pb2 as contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/gateway/cards/cards_gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CardsGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueVirtualCard = channel.unary_unary(
                '/contracts.services.gateway.cards.CardsGatewayService/IssueVirtualCard',
                request_serializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardResponse.FromString,
                _registered_method=True)
        self.IssuePhysicalCard = channel.unary_unary(
                '/contracts.services.gateway.cards.CardsGatewayService/IssuePhysicalCard',
                request_serializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardResponse.FromString,
                _registered_method=True)


class CardsGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IssueVirtualCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssuePhysicalCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardsGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueVirtualCard': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueVirtualCard,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardResponse.SerializeToString,
            ),
            'IssuePhysicalCard': grpc.unary_unary_rpc_method_handler(
                    servicer.IssuePhysicalCard,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.gateway.cards.CardsGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.gateway.cards.CardsGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardsGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IssueVirtualCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.cards.CardsGatewayService/IssueVirtualCard',
            contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__virtual__card__pb2.IssueVirtualCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssuePhysicalCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.cards.CardsGatewayService/IssuePhysicalCard',
            contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_cards_dot_rpc__issue__physical__card__pb2.IssuePhysicalCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
