# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/cards/rpc_issue_virtual_card.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/cards/rpc_issue_virtual_card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.cards import card_pb2 as contracts_dot_services_dot_cards_dot_card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=contracts/services/gateway/cards/rpc_issue_virtual_card.proto\x12 contracts.services.gateway.cards\x1a#contracts/services/cards/card.proto\">\n\x17IssueVirtualCardRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\"H\n\x18IssueVirtualCardResponse\x12,\n\x04\x63\x61rd\x18\x01 \x01(\x0b\x32\x1e.contracts.services.cards.Cardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.cards.rpc_issue_virtual_card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISSUEVIRTUALCARDREQUEST']._serialized_start=136
  _globals['_ISSUEVIRTUALCARDREQUEST']._serialized_end=198
  _globals['_ISSUEVIRTUALCARDRESPONSE']._serialized_start=200
  _globals['_ISSUEVIRTUALCARDRESPONSE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
