"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.documents.tariffs.tariff_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetTariffRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___GetTariffRequest = GetTariffRequest

@typing.final
class GetTariffResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TARIFF_FIELD_NUMBER: builtins.int
    @property
    def tariff(self) -> contracts.services.documents.tariffs.tariff_pb2.Tariff: ...
    def __init__(
        self,
        *,
        tariff: contracts.services.documents.tariffs.tariff_pb2.Tariff | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tariff", b"tariff"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["tariff", b"tariff"]) -> None: ...

global___GetTariffResponse = GetTariffResponse
