# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.documents.tariffs import rpc_create_tariff_pb2 as contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2
from contracts.services.documents.tariffs import rpc_get_tariff_pb2 as contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/documents/tariffs/tariffs_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TariffsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTariff = channel.unary_unary(
                '/contracts.services.documents.tariffs.TariffsService/GetTariff',
                request_serializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffResponse.FromString,
                _registered_method=True)
        self.CreateTariff = channel.unary_unary(
                '/contracts.services.documents.tariffs.TariffsService/CreateTariff',
                request_serializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffResponse.FromString,
                _registered_method=True)


class TariffsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TariffsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTariff,
                    request_deserializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffRequest.FromString,
                    response_serializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffResponse.SerializeToString,
            ),
            'CreateTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTariff,
                    request_deserializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffRequest.FromString,
                    response_serializer=contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.documents.tariffs.TariffsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.documents.tariffs.TariffsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TariffsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.documents.tariffs.TariffsService/GetTariff',
            contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffRequest.SerializeToString,
            contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__get__tariff__pb2.GetTariffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.documents.tariffs.TariffsService/CreateTariff',
            contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffRequest.SerializeToString,
            contracts_dot_services_dot_documents_dot_tariffs_dot_rpc__create__tariff__pb2.CreateTariffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
