"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Tariff(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    DOCUMENT_FIELD_NUMBER: builtins.int
    url: builtins.str
    document: builtins.bytes
    def __init__(
        self,
        *,
        url: builtins.str = ...,
        document: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["document", b"document", "url", b"url"]) -> None: ...

global___Tariff = Tariff
