# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.gateway.operations import rpc_get_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2
from contracts.services.gateway.operations import rpc_get_operation_receipt_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2
from contracts.services.gateway.operations import rpc_get_operations_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2
from contracts.services.gateway.operations import rpc_get_operations_summary_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2
from contracts.services.gateway.operations import rpc_make_bill_payment_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2
from contracts.services.gateway.operations import rpc_make_cash_withdrawal_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2
from contracts.services.gateway.operations import rpc_make_cashback_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2
from contracts.services.gateway.operations import rpc_make_fee_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2
from contracts.services.gateway.operations import rpc_make_purchase_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2
from contracts.services.gateway.operations import rpc_make_top_up_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2
from contracts.services.gateway.operations import rpc_make_transfer_operation_pb2 as contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/gateway/operations/operations_gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationsGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/GetOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.GetOperations = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/GetOperations',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.FromString,
                _registered_method=True)
        self.GetOperationReceipt = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/GetOperationReceipt',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptResponse.FromString,
                _registered_method=True)
        self.GetOperationsSummary = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/GetOperationsSummary',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.FromString,
                _registered_method=True)
        self.MakeFeeOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeFeeOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationResponse.FromString,
                _registered_method=True)
        self.MakeTopUpOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeTopUpOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationResponse.FromString,
                _registered_method=True)
        self.MakeCashbackOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeCashbackOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationResponse.FromString,
                _registered_method=True)
        self.MakePurchaseOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakePurchaseOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationResponse.FromString,
                _registered_method=True)
        self.MakeTransferOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeTransferOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationResponse.FromString,
                _registered_method=True)
        self.MakeBillPaymentOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeBillPaymentOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationResponse.FromString,
                _registered_method=True)
        self.MakeCashWithdrawalOperation = channel.unary_unary(
                '/contracts.services.gateway.operations.OperationsGatewayService/MakeCashWithdrawalOperation',
                request_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationResponse.FromString,
                _registered_method=True)


class OperationsGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeFeeOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeTopUpOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeCashbackOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchaseOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeTransferOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeBillPaymentOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeCashWithdrawalOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.SerializeToString,
            ),
            'GetOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperations,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.SerializeToString,
            ),
            'GetOperationReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationReceipt,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptResponse.SerializeToString,
            ),
            'GetOperationsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationsSummary,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.SerializeToString,
            ),
            'MakeFeeOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeFeeOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationResponse.SerializeToString,
            ),
            'MakeTopUpOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeTopUpOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationResponse.SerializeToString,
            ),
            'MakeCashbackOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCashbackOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationResponse.SerializeToString,
            ),
            'MakePurchaseOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchaseOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationResponse.SerializeToString,
            ),
            'MakeTransferOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeTransferOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationResponse.SerializeToString,
            ),
            'MakeBillPaymentOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeBillPaymentOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationResponse.SerializeToString,
            ),
            'MakeCashWithdrawalOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCashWithdrawalOperation,
                    request_deserializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationRequest.FromString,
                    response_serializer=contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.gateway.operations.OperationsGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.gateway.operations.OperationsGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationsGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/GetOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/GetOperations',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__pb2.GetOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/GetOperationReceipt',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operation__receipt__pb2.GetOperationReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/GetOperationsSummary',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__get__operations__summary__pb2.GetOperationsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeFeeOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeFeeOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__fee__operation__pb2.MakeFeeOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeTopUpOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeTopUpOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__top__up__operation__pb2.MakeTopUpOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeCashbackOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeCashbackOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cashback__operation__pb2.MakeCashbackOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchaseOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakePurchaseOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__purchase__operation__pb2.MakePurchaseOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeTransferOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeTransferOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__transfer__operation__pb2.MakeTransferOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeBillPaymentOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeBillPaymentOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__bill__payment__operation__pb2.MakeBillPaymentOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeCashWithdrawalOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.gateway.operations.OperationsGatewayService/MakeCashWithdrawalOperation',
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationRequest.SerializeToString,
            contracts_dot_services_dot_gateway_dot_operations_dot_rpc__make__cash__withdrawal__operation__pb2.MakeCashWithdrawalOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
