# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/operations/rpc_make_fee_operation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/operations/rpc_make_fee_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.operations import operation_pb2 as contracts_dot_services_dot_operations_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcontracts/services/gateway/operations/rpc_make_fee_operation.proto\x12%contracts.services.gateway.operations\x1a-contracts/services/operations/operation.proto\"\x8e\x01\n\x17MakeFeeOperationRequest\x12>\n\x06status\x18\x02 \x01(\x0e\x32..contracts.services.operations.OperationStatus\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0f\n\x07\x63\x61rd_id\x18\x04 \x01(\t\x12\x12\n\naccount_id\x18\x07 \x01(\t\"W\n\x18MakeFeeOperationResponse\x12;\n\toperation\x18\x01 \x01(\x0b\x32(.contracts.services.operations.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.operations.rpc_make_fee_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAKEFEEOPERATIONREQUEST']._serialized_start=157
  _globals['_MAKEFEEOPERATIONREQUEST']._serialized_end=299
  _globals['_MAKEFEEOPERATIONRESPONSE']._serialized_start=301
  _globals['_MAKEFEEOPERATIONRESPONSE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
