"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.operations.operation_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MakeBillPaymentOperationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    CARD_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    status: contracts.services.operations.operation_pb2.OperationStatus.ValueType
    amount: builtins.float
    card_id: builtins.str
    account_id: builtins.str
    def __init__(
        self,
        *,
        status: contracts.services.operations.operation_pb2.OperationStatus.ValueType = ...,
        amount: builtins.float = ...,
        card_id: builtins.str = ...,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "amount", b"amount", "card_id", b"card_id", "status", b"status"]) -> None: ...

global___MakeBillPaymentOperationRequest = MakeBillPaymentOperationRequest

@typing.final
class MakeBillPaymentOperationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    @property
    def operation(self) -> contracts.services.operations.operation_pb2.Operation: ...
    def __init__(
        self,
        *,
        operation: contracts.services.operations.operation_pb2.Operation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["operation", b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation"]) -> None: ...

global___MakeBillPaymentOperationResponse = MakeBillPaymentOperationResponse
