# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/operations/rpc_get_operations_summary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/operations/rpc_get_operations_summary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.operations import operations_summary_pb2 as contracts_dot_services_dot_operations_dot_operations__summary__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcontracts/services/gateway/operations/rpc_get_operations_summary.proto\x12%contracts.services.gateway.operations\x1a\x36\x63ontracts/services/operations/operations_summary.proto\"1\n\x1bGetOperationsSummaryRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"a\n\x1cGetOperationsSummaryResponse\x12\x41\n\x07summary\x18\x01 \x01(\x0b\x32\x30.contracts.services.operations.OperationsSummaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.operations.rpc_get_operations_summary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOPERATIONSSUMMARYREQUEST']._serialized_start=169
  _globals['_GETOPERATIONSSUMMARYREQUEST']._serialized_end=218
  _globals['_GETOPERATIONSSUMMARYRESPONSE']._serialized_start=220
  _globals['_GETOPERATIONSSUMMARYRESPONSE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
