"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.documents.receipts.receipt_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetOperationReceiptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_ID_FIELD_NUMBER: builtins.int
    operation_id: builtins.str
    def __init__(
        self,
        *,
        operation_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operation_id", b"operation_id"]) -> None: ...

global___GetOperationReceiptRequest = GetOperationReceiptRequest

@typing.final
class GetOperationReceiptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECEIPT_FIELD_NUMBER: builtins.int
    @property
    def receipt(self) -> contracts.services.documents.receipts.receipt_pb2.Receipt: ...
    def __init__(
        self,
        *,
        receipt: contracts.services.documents.receipts.receipt_pb2.Receipt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["receipt", b"receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["receipt", b"receipt"]) -> None: ...

global___GetOperationReceiptResponse = GetOperationReceiptResponse
