"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.operations.operation_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetOperationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetOperationRequest = GetOperationRequest

@typing.final
class GetOperationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    @property
    def operation(self) -> contracts.services.operations.operation_pb2.Operation: ...
    def __init__(
        self,
        *,
        operation: contracts.services.operations.operation_pb2.Operation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["operation", b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation"]) -> None: ...

global___GetOperationResponse = GetOperationResponse
