# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/gateway/operations/rpc_make_top_up_operation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/gateway/operations/rpc_make_top_up_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.operations import operation_pb2 as contracts_dot_services_dot_operations_dot_operation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcontracts/services/gateway/operations/rpc_make_top_up_operation.proto\x12%contracts.services.gateway.operations\x1a-contracts/services/operations/operation.proto\"\x90\x01\n\x19MakeTopUpOperationRequest\x12>\n\x06status\x18\x02 \x01(\x0e\x32..contracts.services.operations.OperationStatus\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0f\n\x07\x63\x61rd_id\x18\x04 \x01(\t\x12\x12\n\naccount_id\x18\x07 \x01(\t\"Y\n\x1aMakeTopUpOperationResponse\x12;\n\toperation\x18\x01 \x01(\x0b\x32(.contracts.services.operations.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.gateway.operations.rpc_make_top_up_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAKETOPUPOPERATIONREQUEST']._serialized_start=160
  _globals['_MAKETOPUPOPERATIONREQUEST']._serialized_end=304
  _globals['_MAKETOPUPOPERATIONRESPONSE']._serialized_start=306
  _globals['_MAKETOPUPOPERATIONRESPONSE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
