# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/payments/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/payments/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)contracts/services/payments/payment.proto\x12\x1b\x63ontracts.services.payments\"\x9e\x01\n\x07Payment\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.contracts.services.payments.PaymentStatus\x12:\n\x06system\x18\x03 \x01(\x0e\x32*.contracts.services.payments.PaymentSystem\x12\x0f\n\x07message\x18\x04 \x01(\t*\xc0\x01\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19PAYMENT_STATUS_AUTHORIZED\x10\x01\x12\x1b\n\x17PAYMENT_STATUS_CAPTURED\x10\x02\x12\x1b\n\x17PAYMENT_STATUS_REFUNDED\x10\x03\x12\x1b\n\x17PAYMENT_STATUS_DECLINED\x10\x04\x12\x19\n\x15PAYMENT_STATUS_FAILED\x10\x05*g\n\rPaymentSystem\x12\x1e\n\x1aPAYMENT_SYSTEM_UNSPECIFIED\x10\x00\x12\x1d\n\x19PAYMENT_SYSTEM_MASTERCARD\x10\x01\x12\x17\n\x13PAYMENT_SYSTEM_VISA\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.payments.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTSTATUS']._serialized_start=236
  _globals['_PAYMENTSTATUS']._serialized_end=428
  _globals['_PAYMENTSYSTEM']._serialized_start=430
  _globals['_PAYMENTSYSTEM']._serialized_end=533
  _globals['_PAYMENT']._serialized_start=75
  _globals['_PAYMENT']._serialized_end=233
# @@protoc_insertion_point(module_scope)
