# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/payments/payments_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/payments/payments_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.payments import rpc_refund_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2
from contracts.services.payments import rpc_capture_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2
from contracts.services.payments import rpc_authorize_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2contracts/services/payments/payments_service.proto\x12\x1b\x63ontracts.services.payments\x1a\x34\x63ontracts/services/payments/rpc_refund_payment.proto\x1a\x35\x63ontracts/services/payments/rpc_capture_payment.proto\x1a\x37\x63ontracts/services/payments/rpc_authorize_payment.proto2\x85\x03\n\x0fPaymentsService\x12v\n\rRefundPayment\x12\x31.contracts.services.payments.RefundPaymentRequest\x1a\x32.contracts.services.payments.RefundPaymentResponse\x12y\n\x0e\x43\x61pturePayment\x12\x32.contracts.services.payments.CapturePaymentRequest\x1a\x33.contracts.services.payments.CapturePaymentResponse\x12\x7f\n\x10\x41uthorizePayment\x12\x34.contracts.services.payments.AuthorizePaymentRequest\x1a\x35.contracts.services.payments.AuthorizePaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.payments.payments_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTSSERVICE']._serialized_start=250
  _globals['_PAYMENTSSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
