# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.payments import rpc_authorize_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2
from contracts.services.payments import rpc_capture_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2
from contracts.services.payments import rpc_refund_payment_pb2 as contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/payments/payments_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RefundPayment = channel.unary_unary(
                '/contracts.services.payments.PaymentsService/RefundPayment',
                request_serializer=contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentResponse.FromString,
                _registered_method=True)
        self.CapturePayment = channel.unary_unary(
                '/contracts.services.payments.PaymentsService/CapturePayment',
                request_serializer=contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentResponse.FromString,
                _registered_method=True)
        self.AuthorizePayment = channel.unary_unary(
                '/contracts.services.payments.PaymentsService/AuthorizePayment',
                request_serializer=contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentResponse.FromString,
                _registered_method=True)


class PaymentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RefundPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CapturePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RefundPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundPayment,
                    request_deserializer=contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentRequest.FromString,
                    response_serializer=contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentResponse.SerializeToString,
            ),
            'CapturePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CapturePayment,
                    request_deserializer=contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentRequest.FromString,
                    response_serializer=contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentResponse.SerializeToString,
            ),
            'AuthorizePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizePayment,
                    request_deserializer=contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentRequest.FromString,
                    response_serializer=contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.payments.PaymentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.payments.PaymentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RefundPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.payments.PaymentsService/RefundPayment',
            contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentRequest.SerializeToString,
            contracts_dot_services_dot_payments_dot_rpc__refund__payment__pb2.RefundPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CapturePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.payments.PaymentsService/CapturePayment',
            contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentRequest.SerializeToString,
            contracts_dot_services_dot_payments_dot_rpc__capture__payment__pb2.CapturePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.payments.PaymentsService/AuthorizePayment',
            contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentRequest.SerializeToString,
            contracts_dot_services_dot_payments_dot_rpc__authorize__payment__pb2.AuthorizePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
