"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.payments.payment_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RefundPaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    PAYMENT_ID_FIELD_NUMBER: builtins.int
    amount: builtins.float
    system: contracts.services.payments.payment_pb2.PaymentSystem.ValueType
    payment_id: builtins.str
    def __init__(
        self,
        *,
        amount: builtins.float = ...,
        system: contracts.services.payments.payment_pb2.PaymentSystem.ValueType = ...,
        payment_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "payment_id", b"payment_id", "system", b"system"]) -> None: ...

global___RefundPaymentRequest = RefundPaymentRequest

@typing.final
class RefundPaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_FIELD_NUMBER: builtins.int
    @property
    def payment(self) -> contracts.services.payments.payment_pb2.Payment: ...
    def __init__(
        self,
        *,
        payment: contracts.services.payments.payment_pb2.Payment | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["payment", b"payment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["payment", b"payment"]) -> None: ...

global___RefundPaymentResponse = RefundPaymentResponse
