# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/payments/rpc_capture_payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/payments/rpc_capture_payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.payments import payment_pb2 as contracts_dot_services_dot_payments_dot_payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5contracts/services/payments/rpc_capture_payment.proto\x12\x1b\x63ontracts.services.payments\x1a)contracts/services/payments/payment.proto\"g\n\x15\x43\x61pturePaymentRequest\x12:\n\x06system\x18\x01 \x01(\x0e\x32*.contracts.services.payments.PaymentSystem\x12\x12\n\npayment_id\x18\x02 \x01(\t\"O\n\x16\x43\x61pturePaymentResponse\x12\x35\n\x07payment\x18\x01 \x01(\x0b\x32$.contracts.services.payments.Paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.payments.rpc_capture_payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPTUREPAYMENTREQUEST']._serialized_start=129
  _globals['_CAPTUREPAYMENTREQUEST']._serialized_end=232
  _globals['_CAPTUREPAYMENTRESPONSE']._serialized_start=234
  _globals['_CAPTUREPAYMENTRESPONSE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
