# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/payments/rpc_authorize_payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/payments/rpc_authorize_payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.payments import payment_pb2 as contracts_dot_services_dot_payments_dot_payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7contracts/services/payments/rpc_authorize_payment.proto\x12\x1b\x63ontracts.services.payments\x1a)contracts/services/payments/payment.proto\"\xb1\x01\n\x17\x41uthorizePaymentRequest\x12\x0b\n\x03\x63vv\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12:\n\x06system\x18\x03 \x01(\x0e\x32*.contracts.services.payments.PaymentSystem\x12\x13\n\x0b\x65xpiry_date\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61rd_holder\x18\x06 \x01(\t\"Q\n\x18\x41uthorizePaymentResponse\x12\x35\n\x07payment\x18\x01 \x01(\x0b\x32$.contracts.services.payments.Paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.payments.rpc_authorize_payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHORIZEPAYMENTREQUEST']._serialized_start=132
  _globals['_AUTHORIZEPAYMENTREQUEST']._serialized_end=309
  _globals['_AUTHORIZEPAYMENTRESPONSE']._serialized_start=311
  _globals['_AUTHORIZEPAYMENTRESPONSE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
