"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.payments.payment_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AuthorizePaymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CVV_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    EXPIRY_DATE_FIELD_NUMBER: builtins.int
    CARD_NUMBER_FIELD_NUMBER: builtins.int
    CARD_HOLDER_FIELD_NUMBER: builtins.int
    cvv: builtins.str
    amount: builtins.float
    system: contracts.services.payments.payment_pb2.PaymentSystem.ValueType
    expiry_date: builtins.str
    card_number: builtins.str
    card_holder: builtins.str
    def __init__(
        self,
        *,
        cvv: builtins.str = ...,
        amount: builtins.float = ...,
        system: contracts.services.payments.payment_pb2.PaymentSystem.ValueType = ...,
        expiry_date: builtins.str = ...,
        card_number: builtins.str = ...,
        card_holder: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "card_holder", b"card_holder", "card_number", b"card_number", "cvv", b"cvv", "expiry_date", b"expiry_date", "system", b"system"]) -> None: ...

global___AuthorizePaymentRequest = AuthorizePaymentRequest

@typing.final
class AuthorizePaymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYMENT_FIELD_NUMBER: builtins.int
    @property
    def payment(self) -> contracts.services.payments.payment_pb2.Payment: ...
    def __init__(
        self,
        *,
        payment: contracts.services.payments.payment_pb2.Payment | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["payment", b"payment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["payment", b"payment"]) -> None: ...

global___AuthorizePaymentResponse = AuthorizePaymentResponse
