# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/accounts/account.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/accounts/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)contracts/services/accounts/account.proto\x12\x1b\x63ontracts.services.accounts\"\xab\x01\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x36\n\x04type\x18\x02 \x01(\x0e\x32(.contracts.services.accounts.AccountType\x12:\n\x06status\x18\x03 \x01(\x0e\x32*.contracts.services.accounts.AccountStatus\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x01*\x9a\x01\n\x0b\x41\x63\x63ountType\x12\x1c\n\x18\x41\x43\x43OUNT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41\x43\x43OUNT_TYPE_DEBIT_CARD\x10\x01\x12\x1c\n\x18\x41\x43\x43OUNT_TYPE_CREDIT_CARD\x10\x02\x12\x18\n\x14\x41\x43\x43OUNT_TYPE_DEPOSIT\x10\x03\x12\x18\n\x14\x41\x43\x43OUNT_TYPE_SAVINGS\x10\x04*\x89\x01\n\rAccountStatus\x12\x1e\n\x1a\x41\x43\x43OUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41\x43\x43OUNT_STATUS_ACTIVE\x10\x01\x12\"\n\x1e\x41\x43\x43OUNT_STATUS_PENDING_CLOSURE\x10\x02\x12\x19\n\x15\x41\x43\x43OUNT_STATUS_CLOSED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.accounts.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTTYPE']._serialized_start=249
  _globals['_ACCOUNTTYPE']._serialized_end=403
  _globals['_ACCOUNTSTATUS']._serialized_start=406
  _globals['_ACCOUNTSTATUS']._serialized_end=543
  _globals['_ACCOUNT']._serialized_start=75
  _globals['_ACCOUNT']._serialized_end=246
# @@protoc_insertion_point(module_scope)
