"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AccountType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AccountTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AccountType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACCOUNT_TYPE_UNSPECIFIED: _AccountType.ValueType  # 0
    ACCOUNT_TYPE_DEBIT_CARD: _AccountType.ValueType  # 1
    ACCOUNT_TYPE_CREDIT_CARD: _AccountType.ValueType  # 2
    ACCOUNT_TYPE_DEPOSIT: _AccountType.ValueType  # 3
    ACCOUNT_TYPE_SAVINGS: _AccountType.ValueType  # 4

class AccountType(_AccountType, metaclass=_AccountTypeEnumTypeWrapper): ...

ACCOUNT_TYPE_UNSPECIFIED: AccountType.ValueType  # 0
ACCOUNT_TYPE_DEBIT_CARD: AccountType.ValueType  # 1
ACCOUNT_TYPE_CREDIT_CARD: AccountType.ValueType  # 2
ACCOUNT_TYPE_DEPOSIT: AccountType.ValueType  # 3
ACCOUNT_TYPE_SAVINGS: AccountType.ValueType  # 4
global___AccountType = AccountType

class _AccountStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AccountStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AccountStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACCOUNT_STATUS_UNSPECIFIED: _AccountStatus.ValueType  # 0
    ACCOUNT_STATUS_ACTIVE: _AccountStatus.ValueType  # 1
    ACCOUNT_STATUS_PENDING_CLOSURE: _AccountStatus.ValueType  # 2
    ACCOUNT_STATUS_CLOSED: _AccountStatus.ValueType  # 3

class AccountStatus(_AccountStatus, metaclass=_AccountStatusEnumTypeWrapper): ...

ACCOUNT_STATUS_UNSPECIFIED: AccountStatus.ValueType  # 0
ACCOUNT_STATUS_ACTIVE: AccountStatus.ValueType  # 1
ACCOUNT_STATUS_PENDING_CLOSURE: AccountStatus.ValueType  # 2
ACCOUNT_STATUS_CLOSED: AccountStatus.ValueType  # 3
global___AccountStatus = AccountStatus

@typing.final
class Account(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    id: builtins.str
    type: global___AccountType.ValueType
    status: global___AccountStatus.ValueType
    user_id: builtins.str
    balance: builtins.float
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type: global___AccountType.ValueType = ...,
        status: global___AccountStatus.ValueType = ...,
        user_id: builtins.str = ...,
        balance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balance", b"balance", "id", b"id", "status", b"status", "type", b"type", "user_id", b"user_id"]) -> None: ...

global___Account = Account
