# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.accounts import rpc_create_account_pb2 as contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2
from contracts.services.accounts import rpc_get_account_pb2 as contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2
from contracts.services.accounts import rpc_get_accounts_pb2 as contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2
from contracts.services.accounts import rpc_update_account_balance_pb2 as contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/accounts/accounts_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccount = channel.unary_unary(
                '/contracts.services.accounts.AccountsService/GetAccount',
                request_serializer=contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.GetAccounts = channel.unary_unary(
                '/contracts.services.accounts.AccountsService/GetAccounts',
                request_serializer=contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/contracts.services.accounts.AccountsService/CreateAccount',
                request_serializer=contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.UpdateAccountBalance = channel.unary_unary(
                '/contracts.services.accounts.AccountsService/UpdateAccountBalance',
                request_serializer=contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceResponse.FromString,
                _registered_method=True)


class AccountsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountResponse.SerializeToString,
            ),
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.FromString,
                    response_serializer=contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountRequest.FromString,
                    response_serializer=contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountResponse.SerializeToString,
            ),
            'UpdateAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccountBalance,
                    request_deserializer=contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceRequest.FromString,
                    response_serializer=contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.accounts.AccountsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.accounts.AccountsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.accounts.AccountsService/GetAccount',
            contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountRequest.SerializeToString,
            contracts_dot_services_dot_accounts_dot_rpc__get__account__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.accounts.AccountsService/GetAccounts',
            contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsRequest.SerializeToString,
            contracts_dot_services_dot_accounts_dot_rpc__get__accounts__pb2.GetAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.accounts.AccountsService/CreateAccount',
            contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountRequest.SerializeToString,
            contracts_dot_services_dot_accounts_dot_rpc__create__account__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.accounts.AccountsService/UpdateAccountBalance',
            contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceRequest.SerializeToString,
            contracts_dot_services_dot_accounts_dot_rpc__update__account__balance__pb2.UpdateAccountBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
