# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/accounts/rpc_get_accounts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/accounts/rpc_get_accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.accounts import account_pb2 as contracts_dot_services_dot_accounts_dot_account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2contracts/services/accounts/rpc_get_accounts.proto\x12\x1b\x63ontracts.services.accounts\x1a)contracts/services/accounts/account.proto\"%\n\x12GetAccountsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"M\n\x13GetAccountsResponse\x12\x36\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32$.contracts.services.accounts.Accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.accounts.rpc_get_accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETACCOUNTSREQUEST']._serialized_start=126
  _globals['_GETACCOUNTSREQUEST']._serialized_end=163
  _globals['_GETACCOUNTSRESPONSE']._serialized_start=165
  _globals['_GETACCOUNTSRESPONSE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
