"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import contracts.services.accounts.account_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateAccountRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    type: contracts.services.accounts.account_pb2.AccountType.ValueType
    status: contracts.services.accounts.account_pb2.AccountStatus.ValueType
    user_id: builtins.str
    balance: builtins.float
    def __init__(
        self,
        *,
        type: contracts.services.accounts.account_pb2.AccountType.ValueType = ...,
        status: contracts.services.accounts.account_pb2.AccountStatus.ValueType = ...,
        user_id: builtins.str = ...,
        balance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balance", b"balance", "status", b"status", "type", b"type", "user_id", b"user_id"]) -> None: ...

global___CreateAccountRequest = CreateAccountRequest

@typing.final
class CreateAccountResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> contracts.services.accounts.account_pb2.Account: ...
    def __init__(
        self,
        *,
        account: contracts.services.accounts.account_pb2.Account | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account"]) -> None: ...

global___CreateAccountResponse = CreateAccountResponse
