# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/accounts/rpc_update_account_balance.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/accounts/rpc_update_account_balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.accounts import account_pb2 as contracts_dot_services_dot_accounts_dot_account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<contracts/services/accounts/rpc_update_account_balance.proto\x12\x1b\x63ontracts.services.accounts\x1a)contracts/services/accounts/account.proto\"B\n\x1bUpdateAccountBalanceRequest\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\x12\x12\n\naccount_id\x18\x02 \x01(\t\"U\n\x1cUpdateAccountBalanceResponse\x12\x35\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32$.contracts.services.accounts.Accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.accounts.rpc_update_account_balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEACCOUNTBALANCEREQUEST']._serialized_start=136
  _globals['_UPDATEACCOUNTBALANCEREQUEST']._serialized_end=202
  _globals['_UPDATEACCOUNTBALANCERESPONSE']._serialized_start=204
  _globals['_UPDATEACCOUNTBALANCERESPONSE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
