# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.services.documents.receipts import rpc_create_receipt_pb2 as contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2
from contracts.services.documents.receipts import rpc_get_receipt_pb2 as contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contracts/services/documents/receipts/receipts_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReceiptsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReceipt = channel.unary_unary(
                '/contracts.services.documents.receipts.ReceiptsService/GetReceipt',
                request_serializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptResponse.FromString,
                _registered_method=True)
        self.CreateReceipt = channel.unary_unary(
                '/contracts.services.documents.receipts.ReceiptsService/CreateReceipt',
                request_serializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptRequest.SerializeToString,
                response_deserializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptResponse.FromString,
                _registered_method=True)


class ReceiptsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptRequest.FromString,
                    response_serializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptResponse.SerializeToString,
            ),
            'CreateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReceipt,
                    request_deserializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptRequest.FromString,
                    response_serializer=contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contracts.services.documents.receipts.ReceiptsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contracts.services.documents.receipts.ReceiptsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceiptsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.documents.receipts.ReceiptsService/GetReceipt',
            contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptRequest.SerializeToString,
            contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2.GetReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contracts.services.documents.receipts.ReceiptsService/CreateReceipt',
            contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptRequest.SerializeToString,
            contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2.CreateReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
