# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/documents/receipts/receipts_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/documents/receipts/receipts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.documents.receipts import rpc_get_receipt_pb2 as contracts_dot_services_dot_documents_dot_receipts_dot_rpc__get__receipt__pb2
from contracts.services.documents.receipts import rpc_create_receipt_pb2 as contracts_dot_services_dot_documents_dot_receipts_dot_rpc__create__receipt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<contracts/services/documents/receipts/receipts_service.proto\x12%contracts.services.documents.receipts\x1a;contracts/services/documents/receipts/rpc_get_receipt.proto\x1a>contracts/services/documents/receipts/rpc_create_receipt.proto2\xa2\x02\n\x0fReceiptsService\x12\x81\x01\n\nGetReceipt\x12\x38.contracts.services.documents.receipts.GetReceiptRequest\x1a\x39.contracts.services.documents.receipts.GetReceiptResponse\x12\x8a\x01\n\rCreateReceipt\x12;.contracts.services.documents.receipts.CreateReceiptRequest\x1a<.contracts.services.documents.receipts.CreateReceiptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.documents.receipts.receipts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIPTSSERVICE']._serialized_start=229
  _globals['_RECEIPTSSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
