# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/services/documents/receipts/rpc_create_receipt.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'contracts/services/documents/receipts/rpc_create_receipt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.services.documents.receipts import receipt_pb2 as contracts_dot_services_dot_documents_dot_receipts_dot_receipt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>contracts/services/documents/receipts/rpc_create_receipt.proto\x12%contracts.services.documents.receipts\x1a\x33\x63ontracts/services/documents/receipts/receipt.proto\"=\n\x14\x43reateReceiptRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"X\n\x15\x43reateReceiptResponse\x12?\n\x07receipt\x18\x01 \x01(\x0b\x32..contracts.services.documents.receipts.Receiptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.services.documents.receipts.rpc_create_receipt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERECEIPTREQUEST']._serialized_start=158
  _globals['_CREATERECEIPTREQUEST']._serialized_end=219
  _globals['_CREATERECEIPTRESPONSE']._serialized_start=221
  _globals['_CREATERECEIPTRESPONSE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
