name: Performance Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      SCENARIO:
        type: 'choice'
        default: 'tests/grpc/gateway/new_user_get_accounts/v1.conf'
        options:
          - tests/grpc/gateway/existing_user_get_documents/v1.conf
          - tests/grpc/gateway/existing_user_get_operations/v1.conf
          - tests/grpc/gateway/existing_user_issue_virtual_card/v1.conf
          - tests/grpc/gateway/existing_user_make_purchase_operation/v1.conf
          - tests/grpc/gateway/new_user_get_accounts/v1.conf
          - tests/grpc/gateway/new_user_get_documents/v1.conf
          - tests/grpc/gateway/new_user_issue_physical_card/v1.conf
          - tests/grpc/gateway/new_user_make_top_up_operation/v1.conf

          - tests/http/gateway/existing_user_get_documents/v1.conf
          - tests/http/gateway/existing_user_get_operations/v1.conf
          - tests/http/gateway/existing_user_issue_virtual_card/v1.conf
          - tests/http/gateway/existing_user_make_purchase_operation/v1.conf
          - tests/http/gateway/new_user_get_accounts/v1.conf
          - tests/http/gateway/new_user_get_documents/v1.conf
          - tests/http/gateway/new_user_issue_physical_card/v1.conf
          - tests/http/gateway/new_user_make_top_up_operation/v1.conf
        required: true
        description: 'Locust config file'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.12'

      - name: Clone test services
        run: git clone https://github.com/Nikita-Filonov/performance-qa-engineer-course.git

      - name: Build base Docker image
        run: docker build -f Dockerfile.base -t base-service .
        working-directory: performance-qa-engineer-course

      - name: Start test services
        run: docker compose -f docker-compose.ci.yaml up -d --build
        working-directory: performance-qa-engineer-course

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --frozen

      - name: Create report directory
        run: mkdir -p reports/${{ github.run_id }}

      - name: Run load tests and generate HTML report
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SCENARIO="${{ github.event.inputs.SCENARIO }}"
          else
            SCENARIO="tests/grpc/gateway/new_user_get_accounts/v1.conf"
          fi

          uv run locust \
            --config="$SCENARIO" \
            --html=reports/${{ github.run_id }}/index.html

      - name: Set latest report
        run: cp reports/${{ github.run_id }}/index.html reports/index.html

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: locust-report
          path: reports

      - name: Stop test services
        if: always()
        run: docker compose -f docker-compose.ci.yaml down -v
        working-directory: performance-qa-engineer-course

  publish-report:
    runs-on: ubuntu-latest
    needs: run-tests
    if: always()

    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: locust-report
          path: reports

      - name: Deploy HTML report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: reports
          publish_branch: gh-pages
